# Generated by Django 6.0.3 on 2026-03-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VegetablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=200)),
                ('commodity_unit', models.CharField(default='KG', max_length=50)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'commodity_name'],
                'indexes': [models.Index(fields=['commodity_name', 'date'], name='prices_vege_commodi_656834_idx'), models.Index(fields=['date'], name='prices_vege_date_f86506_idx')],
                'unique_together': {('commodity_name', 'date')},
            },
        ),
    ]
